[package]
edition = "2024"
name = "explicit-error-derive"
version = "0.1.0"

[lib]
proc-macro = true

[features]
actix-web = ["http"]
exit = []
http = []

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
